pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: "ce-pipelines"
      type: "github"
      name: "cloudextend/templates-pipelines"
      endpoint: "GitHub BuildBot PAT"
      ref: "refs/tags/v7.0.1"

stages:
  - stage: "stageNuGetPackageDeployment"
    displayName: "Build and Publish NuGet Package"
    jobs:
      - job: "jobBuildPublishNuGetPackage"
        steps:
          - template: "steps/checkout.yml@ce-pipelines"

          - template: "templates/push-nupkg.yml@ce-pipelines"
            parameters:
              ProjectName: "$(Build.DefinitionName)"
              GitHubPackagesPAT: "$(GitHubPackagesPAT)"
              NuGetPackagesPAT: "$(NuGetPackagesPAT)"
              NuGetConfigPath: "$(NuGetConfigPath)"
              PackageDestination: "CloudExtend"
              WorkingDir: "$(WorkingDir)"
